/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.suwadharani;

import java.sql.*;
import javax.swing.JOptionPane;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.ButtonGroup;
import javax.swing.table.TableModel;
/**
 *
 * @author Janitha Theekshana
 */
public class EnterAllCitizenDetails extends javax.swing.JFrame {

    /**
     * Creates new form EnterAllCitizenDetails
     */
    public EnterAllCitizenDetails() {
        initComponents();
        table();
       ID();
    }   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
       public void clear()
    {
        fid.setText("");
        add.setText("");
        name.setText("");
        dob.setCalendar(null); 
        vac_name.setSelectedIndex(0);
        vac_doss.setSelectedIndex(0);
        buttonGroup2.clearSelection();
        buttonGroup1.clearSelection();
        ID();
    }
       
        public void table(){
              DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
              model.setRowCount(0);
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            java.sql.Connection con = (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/coviddb","root","");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from village_citizen");
            
            while(rs.next())
            {
                model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9)}) ;
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
       }
       
      
       public void ID()
    {
          try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/coviddb","root","");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select count(P_ID) from village_citizen");
            if(rs.next())
            {
                int regNo = rs.getInt(1);
                regNo = regNo+1;
                String str = String.valueOf(regNo);
                count.setText(str);
            }
            else
                count.setText("1");
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        add = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        fid = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        no = new javax.swing.JRadioButton();
        yes = new javax.swing.JRadioButton();
        vac_name = new javax.swing.JComboBox<>();
        vac_doss = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        enterBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        dob = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        jButton2 = new javax.swing.JButton();
        count = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 100));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(27, 155, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 55)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(27, 155, 255));
        jLabel1.setText("Enter Citizen Details");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(311, 311, 311)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(339, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 3, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 70));

        add.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 420, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Family id");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Vaccine Doss");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 240, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Address");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Date Of Birth");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id", "Family ID", "Full Name", "Address", "Date of Birth", "Gender", "Vaccinate", "Vaccine Name", "Vaccine Doss"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setToolTipText("");
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 340, 1190, 300));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Full Name");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Gender");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Vaccine Name");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 200, -1, -1));

        fid.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(fid, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 70, -1));

        name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 420, -1));

        no.setBackground(new java.awt.Color(27, 155, 255));
        buttonGroup2.add(no);
        no.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        no.setForeground(new java.awt.Color(255, 255, 255));
        no.setText("NO");
        no.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                noItemStateChanged(evt);
            }
        });
        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });
        jPanel1.add(no, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 160, -1, -1));

        yes.setBackground(new java.awt.Color(27, 155, 255));
        buttonGroup2.add(yes);
        yes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        yes.setForeground(new java.awt.Color(255, 255, 255));
        yes.setText("YES");
        yes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                yesItemStateChanged(evt);
            }
        });
        yes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yesActionPerformed(evt);
            }
        });
        jPanel1.add(yes, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 160, -1, -1));

        vac_name.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        vac_name.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No", "Sinopharm", "Pfizer", "Moderna", "Jonson & Jonson", "Sputnic V", "Astrasenica", "Sinovac", " " }));
        vac_name.setToolTipText("");
        vac_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vac_nameActionPerformed(evt);
            }
        });
        jPanel1.add(vac_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 200, -1, -1));

        vac_doss.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        vac_doss.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2", "3", "" }));
        vac_doss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vac_dossActionPerformed(evt);
            }
        });
        jPanel1.add(vac_doss, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 240, -1, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("CLEAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, -1, -1));

        enterBtn.setBackground(new java.awt.Color(0, 204, 0));
        enterBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterBtn.setForeground(new java.awt.Color(255, 255, 255));
        enterBtn.setText("ENTER");
        enterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterBtnActionPerformed(evt);
            }
        });
        jPanel1.add(enterBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 290, -1, -1));

        jPanel3.setBackground(new java.awt.Color(255, 0, 0));

        jLabel9.setBackground(new java.awt.Color(255, 0, 0));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("X");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1190, 80, 40, 40));
        jPanel1.add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 240, 270, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Vaccinate");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, -1, -1));

        male.setBackground(new java.awt.Color(27, 155, 255));
        buttonGroup1.add(male);
        male.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        male.setForeground(new java.awt.Color(255, 255, 255));
        male.setText("Male");
        male.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                maleItemStateChanged(evt);
            }
        });
        male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleActionPerformed(evt);
            }
        });
        jPanel1.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 120, -1, -1));

        female.setBackground(new java.awt.Color(27, 155, 255));
        buttonGroup1.add(female);
        female.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        female.setForeground(new java.awt.Color(255, 255, 255));
        female.setText("Female");
        female.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                femaleItemStateChanged(evt);
            }
        });
        female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleActionPerformed(evt);
            }
        });
        jPanel1.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 120, -1, -1));

        jButton2.setBackground(new java.awt.Color(0, 0, 153));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("EDIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, -1, -1));

        count.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        count.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(count, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 50, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
         int a= JOptionPane.showConfirmDialog(this,"Do you really want to close this page","Close",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
     if(a==0)
     {
          setVisible(false);
     }    
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        clear();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void enterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterBtnActionPerformed
         // TODO add your handling code here:
        String cou = count.getText();
        String family_id = fid.getText();
       
        String name1 = name.getText();
        String address = add.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("yyy-MM-dd");
        String DOB = sdf.format(dob.getDate());
        String vaccine_name = (String)vac_name.getSelectedItem();
        String vaccine_doss = (String)vac_doss.getSelectedItem();
        //String vaccine_name = (String)vac_name.getSelectedItem();
        
        
        if(family_id.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter Family Id");
        } 
        if(name1.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter Name");
        }
        if(address.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter Address");
        }
        if(DOB.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter Date of Birth");
        }
         if(family_id.matches("^[0-9]*$"))
        {
             if(name1.matches("^[A-Z a-z]*$"))
        {
         try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            java.sql.Connection con = (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/coviddb","root","");
            PreparedStatement ps = con.prepareStatement("INSERT INTO village_citizen VALUES(?,?,?,?,?,?,?,?,?)");
             ps.setString(1, cou);
            ps.setString(2, family_id);
            ps.setString(3, name1);
            ps.setString(4, address);
            ps.setString(5, DOB);
            ps.setString(6, gender);
            ps.setString(7, vaccinate);
            ps.setString(8, vaccine_name);
            ps.setString(9, vaccine_doss);
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Successfully Updated");
            clear();
            table();
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        }
             else{
                 JOptionPane.showMessageDialog(null, "Name field can insert letters only");
             }
         }
        else{
            JOptionPane.showMessageDialog(null,"Family id field can insert numbers only");
        }
    }//GEN-LAST:event_enterBtnActionPerformed

    private void yesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yesActionPerformed
        // TODO add your handling code here:
        vaccinate = "yes";
        vac_name.setVisible(true);
        vac_doss.setVisible(true);
    }//GEN-LAST:event_yesActionPerformed

    private void noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionPerformed
        // TODO add your handling code here:
        vaccinate = "no";
        vac_name.setVisible(false);
        vac_doss.setVisible(false);
        vac_name.setSelectedIndex(0);
        vac_doss.setSelectedIndex(0);
    }//GEN-LAST:event_noActionPerformed

    private void maleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleActionPerformed
        // TODO add your handling code here:
        gender = "Male";
    }//GEN-LAST:event_maleActionPerformed

    private void femaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleActionPerformed
        // TODO add your handling code here:
        gender = "Female";
    }//GEN-LAST:event_femaleActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String f_id = fid.getText();
        String Name = name.getText();
        String address = add.getText();
        SimpleDateFormat sdf1 = new SimpleDateFormat("yyy-MM-dd");
        String Date = sdf1.format(dob.getDate());
        String vaccine_name = (String)vac_name.getSelectedItem();
        String vaccine_doss = (String)vac_doss.getSelectedItem();
        String c = count.getText();
        
         if(Name.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter Name");
        }
        if(address.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter Address");
        }
        if(Date.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter Date of Birth");
        }
         if(f_id.matches("^[0-9]*$"))
        {
             if(Name.matches("^[A-Z a-z]*$"))
        {
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/coviddb","root","");
            PreparedStatement ps = con.prepareStatement("UPDATE village_citizen SET family_id=? ,name=? , address=?,DOB=? ,gender=? ,vaccinate=?, vaccine_name=?, vaccine_doss=? where P_ID='"+c+"'");
            
            ps.setString(1, f_id);
            ps.setString(2, Name);
            ps.setString(3, address);
            ps.setString(4, Date);
            ps.setString(5, Gender);
            ps.setString(6, Vaccinate);
            ps.setString(7, vaccine_name);
            ps.setString(8, vaccine_doss);
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Successfully Updated");
            clear();
            table();
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
        }
         else{
                 JOptionPane.showMessageDialog(null, "Name field can insert letters only");
             }
         }
        else{
            JOptionPane.showMessageDialog(null,"Family id field can insert numbers only");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int i = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        count.setText(model.getValueAt(i,0).toString());
        fid.setText(model.getValueAt(i,1).toString());
        name.setText(model.getValueAt(i,2).toString());
        add.setText(model.getValueAt(i,3).toString());
        try { 
            java.util.Date date =new SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(i, 4).toString());
            dob.setDate(date);
        } catch (ParseException ex) {
            Logger.getLogger(EnterAllCitizenDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
        String gender = model.getValueAt(i,5).toString();
         if(gender.equals("Male")){
             male.setSelected(true);
         }
         else{
             female.setSelected(true);
         }
         String vaccinate = model.getValueAt(i,6).toString();
         if(vaccinate.equals("yes")){
             yes.setSelected(true);
         }
         else{
             no.setSelected(true);
         }
       String vacName = model.getValueAt(i, 7).toString();
            switch(vacName){
                case"0":
                        vac_name.setSelectedIndex(0);
                        break;
                case "Sinopharm":
                        vac_name.setSelectedIndex(1);
                        break;
                case "Pfizer":
                        vac_name.setSelectedIndex(2);
                        break;
                case "Moderna":
                        vac_name.setSelectedIndex(3);
                        break;
                case "Jonson & Jonson":
                        vac_name.setSelectedIndex(4);
                        break;
                case "Sputnic V":
                        vac_name.setSelectedIndex(5);
                        break;
                case "Astrasenica":
                        vac_name.setSelectedIndex(6);
                        break;
                default:
                        vac_name.setSelectedIndex(7);
            }
        String vacDoss = model.getValueAt(i, 8).toString();
            switch(vacDoss){
                case "0":
                        vac_doss.setSelectedIndex(0);
                        break;
                case "1":
                        vac_doss.setSelectedIndex(1);
                        break;
                case "2":
                        vac_doss.setSelectedIndex(2);
                        break;
                default:
                        vac_doss.setSelectedIndex(3);
            }
    }//GEN-LAST:event_jTable1MouseClicked

    private void femaleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_femaleItemStateChanged
        // TODO add your handling code here:
        Gender="Female";
    }//GEN-LAST:event_femaleItemStateChanged

    private void maleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_maleItemStateChanged
        // TODO add your handling code here:
        Gender="Male";
    }//GEN-LAST:event_maleItemStateChanged

    private void yesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_yesItemStateChanged
        // TODO add your handling code here:
         Vaccinate = "yes";
    }//GEN-LAST:event_yesItemStateChanged

    private void noItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_noItemStateChanged
        // TODO add your handling code here:
         Vaccinate = "no";
    }//GEN-LAST:event_noItemStateChanged

    private void vac_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vac_nameActionPerformed
        // TODO add your handling code here:
        String vaccine_name = (String)vac_name.getSelectedItem();
    }//GEN-LAST:event_vac_nameActionPerformed

    private void vac_dossActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vac_dossActionPerformed
        // TODO add your handling code here:
        String vaccine_doss = (String)vac_doss.getSelectedItem();
    }//GEN-LAST:event_vac_dossActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnterAllCitizenDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnterAllCitizenDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnterAllCitizenDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnterAllCitizenDetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnterAllCitizenDetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel count;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JButton enterBtn;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField fid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField name;
    private javax.swing.JRadioButton no;
    private javax.swing.JComboBox<String> vac_doss;
    private javax.swing.JComboBox<String> vac_name;
    private javax.swing.JRadioButton yes;
    // End of variables declaration//GEN-END:variables

private String vaccinate;
private String Vaccinate;
private String gender;
private String Gender;
private String vaccine_name;
private String vaccine_doss;
}
