/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.suwadharani;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Janitha Theekshana
 */
public class EnterCovidDeaths extends javax.swing.JFrame {

    /**
     * Creates new form EnterCovidDeaths
     */
    public EnterCovidDeaths() {
        initComponents();
        table();
        ID();
    }
    
    public void clear()
    {
    jTextField7.setText("");
    date.setCalendar(null);
    fid.setText("");
    nametxt.setText("");
    add.setText("");
    dob.setCalendar(null);
    buttonGroup1.clearSelection();
    vac.setText("");
    vacName.setText("");
    vacDoss.setText("");
    dReason.setText("");
    }
    
    public void table()
    {
          DefaultTableModel model = (DefaultTableModel)jTable1.getModel();
              model.setRowCount(0);
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            java.sql.Connection con = (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/coviddb","root","");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select * from death_people");
            
            while(rs.next())
            {
                model.addRow(new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(4),rs.getString(5),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10),rs.getString(11)}) ;
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
    }
    
    public void ID()
    {
          try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/coviddb","root","");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("select count(Dp_Id) from death_people");
            if(rs.next())
            {
                int regNo = rs.getInt(1);
                regNo = regNo+1;
                String str = String.valueOf(regNo);
                dpID.setText(str);
            }
            else
                dpID.setText("1");
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    
    public void delete()
    {
    try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            java.sql.Connection con = (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/coviddb","root","");
              PreparedStatement ps = con.prepareStatement("DELETE village_citizen.* from village_citizen Inner Join death_people on village_citizen.name = death_people.name");
              ps.executeUpdate();
        }catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
        }
    }
    
     public void deleteQ()
    {
    try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            java.sql.Connection con = (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/coviddb","root","");
            //PreparedStatement ps = con.prepareStatement("DELETE FROM village_citizen WHERE name = name");
              PreparedStatement ps = con.prepareStatement("DELETE quarantine_people.* from quarantine_people Inner Join death_people on quarantine_people.name = death_people.name");
              ps.executeUpdate();
        }catch(Exception e){
             JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        vacName = new javax.swing.JTextField();
        add = new javax.swing.JTextField();
        vac = new javax.swing.JTextField();
        vacDoss = new javax.swing.JTextField();
        nametxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        dReason = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        fid = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        dob = new com.toedter.calendar.JDateChooser();
        date = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        male = new javax.swing.JRadioButton();
        female = new javax.swing.JRadioButton();
        dpID = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(100, 100));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(27, 155, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(1260, 70));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 55)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(27, 155, 255));
        jLabel1.setText("Covid Deaths Details");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(333, 333, 333)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(342, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 70));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Death people id:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Full Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Address");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Gender");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Death Reason");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 530, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Vaccinate");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Vaccine Name");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Vaccine Doss");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, -1, -1));
        jPanel1.add(vacName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 270, 30));
        jPanel1.add(add, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 280, 270, 30));
        jPanel1.add(vac, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 270, 30));
        jPanel1.add(vacDoss, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, 270, 30));
        jPanel1.add(nametxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 270, 30));

        dReason.setColumns(20);
        dReason.setRows(5);
        jScrollPane1.setViewportView(dReason);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 520, 270, 100));

        jPanel3.setBackground(new java.awt.Color(255, 0, 0));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 28)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("X");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 80, 40, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Name");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 120, -1, -1));

        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, 190, 30));

        jButton1.setBackground(new java.awt.Color(204, 0, 204));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Dp_id", "Date", "Family ID", "Full Name             ", "Address", "DOB", "Gender", "Vaccinate", "Vaccine Name", "Vaccine Doss ", "Death Reason"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 240, 800, 300));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Family ID");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));
        jPanel1.add(fid, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 270, 30));

        jButton2.setBackground(new java.awt.Color(255, 255, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton2.setText("CLEAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 580, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 0, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton3.setText("UPDATE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 580, 110, -1));

        jButton4.setBackground(new java.awt.Color(0, 255, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jButton4.setText("ENTER");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 580, -1, -1));
        jPanel1.add(dob, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 270, 30));
        jPanel1.add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 160, 270, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("DOB");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        male.setBackground(new java.awt.Color(27, 155, 255));
        buttonGroup1.add(male);
        male.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        male.setForeground(new java.awt.Color(255, 255, 255));
        male.setText("Male");
        male.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                maleItemStateChanged(evt);
            }
        });
        jPanel1.add(male, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 360, -1, -1));

        female.setBackground(new java.awt.Color(27, 155, 255));
        buttonGroup1.add(female);
        female.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        female.setForeground(new java.awt.Color(255, 255, 255));
        female.setText("Female");
        female.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                femaleItemStateChanged(evt);
            }
        });
        jPanel1.add(female, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, -1, -1));

        dpID.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        dpID.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(dpID, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, 60, 50));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Date");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 640, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        // TODO add your handling code here:
     int a= JOptionPane.showConfirmDialog(this,"Do you really want to close this page","Close",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
     if(a==0)
     {
          setVisible(false);
     }    
    }//GEN-LAST:event_jLabel11MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           String name = jTextField7.getText();
        int i=0;
        ResultSet rs;
          
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/coviddb","root","");
            PreparedStatement ps = con.prepareStatement("SELECT family_id, name, address,DOB,gender, vaccinate, vaccine_name, vaccine_doss FROM village_citizen WHERE name LIKE ?");
            ps.setString(1, name);
           
            rs = ps.executeQuery();
            
             while(rs.next())
            {
                fid.setText(rs.getString("family_id"));
                nametxt.setText(rs.getString("name"));
                add.setText(rs.getString("address"));
                dob.setDate(rs.getDate("DOB"));
                String gender = rs.getString("gender");
                {
                    if(gender.equals("female")){
                        male.setSelected(false);
                        female.setSelected(true);
                    }else{
                        female.setSelected(false);
                        male.setSelected(true);
                    }
                }
               
                
                vac.setText(rs.getString("vaccinate"));
                vacName.setText(rs.getString("vaccine_name"));
                vacDoss.setText(rs.getString("vaccine_doss"));
               
            }
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        String dp_id = dpID.getText();
        SimpleDateFormat sdf1 = new SimpleDateFormat("yyy-MM-dd");
        String Date = sdf1.format(date.getDate());
        String family_id = fid.getText();
        String name = nametxt.getText();
        String address = add.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("yyy-MM-dd");
        String DOB = sdf.format(dob.getDate());
        String vaccinate = vac.getText();
        String vaccine_name = vacName.getText();
        String vaccine_doss = vacDoss.getText();
        String death_reason = dReason.getText();
        
          if(Date.equals("")){
            JOptionPane.showMessageDialog(null, "Please enter Name");
        }else{
        
         try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            java.sql.Connection con = (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/coviddb","root","");
            PreparedStatement ps = con.prepareStatement("INSERT INTO death_people VALUES(?,?,?,?,?,?,?,?,?,?,?)");
            ps.setString(1, dp_id);
            ps.setString(2, Date);
            ps.setString(3, family_id);
            ps.setString(4, name);
            ps.setString(5, address);
            ps.setString(6, DOB);
            ps.setString(7, gender);
            ps.setString(8, vaccinate);
            ps.setString(9, vaccine_name);
            ps.setString(10, vaccine_doss);
            ps.setString(11, death_reason);
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Successfully Updated");
            
            delete();
            deleteQ();
            clear();
            table();
            ID();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }  
          }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void maleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_maleItemStateChanged
        // TODO add your handling code here:
        gender = "Male";
    }//GEN-LAST:event_maleItemStateChanged

    private void femaleItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_femaleItemStateChanged
        // TODO add your handling code here:
        gender = "female";
    }//GEN-LAST:event_femaleItemStateChanged

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int a= JOptionPane.showConfirmDialog(this,"Do you really want to clear all rows","Clear",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
     if(a==0)
     {
          clear();
     }    
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String dp_id = dpID.getText();
        SimpleDateFormat sdf1 = new SimpleDateFormat("yyyy-MM-dd");
        String Date = sdf1.format(date.getDate());
        String family_id = fid.getText();
        String name = nametxt.getText();
        String address = add.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String DOB = sdf.format(dob.getDate());
        String vaccinate = vac.getText();
        String vaccine_name = vacName.getText();
        String vaccine_doss = vacDoss.getText();
        String death_reason = dReason.getText();
        
        try
        {
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost:3306/coviddb","root","");
            PreparedStatement ps = con.prepareStatement("UPDATE death_people SET Date=?, family_id=? ,name=? , address=?,Date_Of_Birth=? ,gender=? ,vaccinate=?, vaccine_name=?, vaccine_doss=?, death_reason=? where DP_Id='"+dp_id+"'");
            
            ps.setString(1, Date);
            ps.setString(2, family_id);
            ps.setString(3, name);
            ps.setString(4, address);
            ps.setString(5, DOB);
            ps.setString(6, gender);
            ps.setString(7, vaccinate);
            ps.setString(8, vaccine_name);
            ps.setString(9, vaccine_doss);
            ps.setString(10, death_reason);
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Successfully Updated");
            clear();
            table();
            
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
         int i = jTable1.getSelectedRow();
        TableModel model = jTable1.getModel();
        dpID.setText(model.getValueAt(i,0).toString());
        try { 
            java.util.Date date1 =new SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(i, 1).toString());
            date.setDate(date1);
        } catch (ParseException ex) {
            Logger.getLogger(EnterAllCitizenDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
         fid.setText(model.getValueAt(i,2).toString());
         nametxt.setText(model.getValueAt(i,3).toString());
         add.setText(model.getValueAt(i,4).toString());
        try { 
            java.util.Date date2 =new SimpleDateFormat("yyyy-MM-dd").parse((String)model.getValueAt(i, 5).toString());
            dob.setDate(date2);
        } catch (ParseException ex) {
            Logger.getLogger(EnterAllCitizenDetails.class.getName()).log(Level.SEVERE, null, ex);
        }
        String gender = model.getValueAt(i,6).toString();
         if(gender.equals("Male")){
             male.setSelected(true);
         }
         else{
             female.setSelected(true);
         }
         vac.setText(model.getValueAt(i,7).toString());
         vacName.setText(model.getValueAt(i,8).toString());
         vacDoss.setText(model.getValueAt(i,9).toString());
         dReason.setText(model.getValueAt(i,10).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnterCovidDeaths.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnterCovidDeaths.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnterCovidDeaths.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnterCovidDeaths.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnterCovidDeaths().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField add;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextArea dReason;
    private com.toedter.calendar.JDateChooser date;
    private com.toedter.calendar.JDateChooser dob;
    private javax.swing.JLabel dpID;
    private javax.swing.JRadioButton female;
    private javax.swing.JTextField fid;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JRadioButton male;
    private javax.swing.JTextField nametxt;
    private javax.swing.JTextField vac;
    private javax.swing.JTextField vacDoss;
    private javax.swing.JTextField vacName;
    // End of variables declaration//GEN-END:variables
private String gender;
}
